-- CreateTable
CREATE TABLE "Spaces" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "name" TEXT NOT NULL,
    "description" TEXT NOT NULL,
    "color" TEXT NOT NULL,
    "icon" TEXT NOT NULL,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL
);

-- CreateTable
CREATE TABLE "Elements" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "e_type" TEXT NOT NULL,
    "value" TEXT NOT NULL,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL,
    "spacesId" INTEGER NOT NULL,
    CONSTRAINT "Elements_spacesId_fkey" FOREIGN KEY ("spacesId") REFERENCES "Spaces" ("id") ON DELETE RESTRICT ON UPDATE CASCADE
);
