// This file was generated by [rspc](https://github.com/oscartbeaumont/rspc). Do not edit this file manually.

export type Operations = {
    queries: 
        { key: ["e"], result: string },
    mutations: never,
    subscriptions: never
};
