-- CreateTable
CREATE TABLE "Elements" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "type" TEXT NOT NULL,
    "content" TEXT NOT NULL,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "spacesId" INTEGER NOT NULL,
    CONSTRAINT "Elements_spacesId_fkey" FOREIGN KEY ("spacesId") REFERENCES "spaces" ("id") ON DELETE RESTRICT ON UPDATE CASCADE
);
