/* eslint-disable */
// This file was generated by [rspc](https://github.com/oscartbeaumont/rspc). Do not edit this file manually.

export type Procedures = {
    queries: 
        { key: "misc.run_migrations", input: never, result: null } | 
        { key: "version", input: never, result: string },
    mutations: never,
    subscriptions: never
};
