/* eslint-disable no-mixed-spaces-and-tabs */
// This file was generated by [rspc](https://github.com/oscartbeaumont/rspc). Do not edit this file manually.

export type Operations = {
	queries:
		| { key: ['elements.get']; result: Array<Elements> }
		| { key: ['spaces.get']; result: Array<Spaces> };
	mutations:
		| {
				key: ['spaces.updateSpaceIndexes', UpdateSpaceIndexesArgs];
				result: null;
		  }
		| { key: ['spaces.create']; result: Spaces }
		| { key: ['elements.create', CreateElementDataArgs]; result: null };
	subscriptions: never;
};

export interface Elements {
	id: number;
	elementType: string;
	content: string;
	space: Spaces | null;
	positionX: number;
	positionY: number;
	createdAt: string;
	updatedAt: string;
	spaceId: number;
}

export interface UpdateSpaceIndexesArgs {
	spaces: Array<Spaces>;
}

export interface Spaces {
	id: number;
	name: string;
	description: string;
	icon: string;
	color: string;
	index: number;
	createdAt: string;
	updatedAt: string;
	Elements: Array<Elements> | null;
}

export interface Element {
	content: string;
	type: string;
}

export interface CreateElementDataArgs {
	space_id: number;
	type: string;
	value: Array<Element>;
}
